spring:
  config:
    import: "optional:configserver:http://config-server:8888"
    activate:
      on-profile: docker
---
spring:
  application:
    name: notification-service
  config:
    import: "optional:configserver:http://localhost:8888"