spring:
  config:
    activate:
      on-profile: local
server:
  port: ${SERVER_PORT:5761}

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0

