spring:
  config:
    import: ${CONFIG_FULL_URL:optional:configserver:http://config-server:8888}
    activate:
      on-profile: docker
  application:
    name: discovery-server
---
spring:
  application:
    name: discovery-server
  config:
    import: "optional:configserver:http://localhost:8888"