server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/halilcakmak34/abc-otel-config.git
          search-paths: 'application'


logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){blue} %clr(${LOG_LEVEL_PATTERN:-%5p}) %m%n"