server.port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/halilcakmak34/abc-otel-example/config-service/src/main/resources/shared
          default-label: main
        native:
          searchLocations: file:///${GIT_REPO}


