spring:
  application:
    name: config-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

--- #DOCKER
spring:
  config:
    activate:
      on-profile: docker
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared-docker

server:
  port: 8888