server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        #git:
          #uri: file:///Users/admin-halil/Documents/dev-otel-example/abc-otel-example/config-server/src/main/resources/shared
        native:
          search-locations: classpath:/shared