server.port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/halilcakmak34/abc-otel-config
          default-label: main
        native:
          searchLocations: file:///${GIT_REPO}

management:
  endpoints:
    web:
      exposure:
        include: *

logging.level.org.springframework.cloud: trace


