
spring:
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:4900/otel-db}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    hikari:
      connection-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 15
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  zipkin:
    base-url: ${ZIPKIN_FULL_URL:http://localhost:9411}
    enabled: true
    service:
      name: otel-service
    message-timeout: 10
    sleuth:
      sampler:
        probability: 1.0
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
  kafka:
    bootstrap-servers: ${KAFKA_FULL_URL:localhost:9092}
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    topics:
      test:
        name: test-topic
        partitions: 1
        replication-factor: 1
      reservation:
        name: reservation-topic
        partitions: 1
        replication-factor: 1
      abc-logger:
        name: abc-logger-topic
        partitions: 1
        replication-factor: 1

springdoc:
  packagesToScan: com.oteller.example.otel
  cache:
    disabled: false
  version: '@springdoc.version@'
  api-docs:
    version: openapi_3_1

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_FULL_URL:http://localhost:5761/eureka/}
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){blue} %clr([%X{traceId:-},%X{spanId:-}]){cyan} %clr(${LOG_LEVEL_PATTERN:-%5p}) %m%n"

server:
  port: ${SERVER_PORT:0}
  forward-headers-strategy: framework
  servlet:
    context-path: /api


management:
  tracing:
    sampling:
      probability: 1.0
